# Generated by Django 4.1.7 on 2023-02-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0002_alter_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='pokemons',
        ),
    ]
