# Generated by Django 4.1.7 on 2023-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
