# Generated by Django 4.1.7 on 2023-02-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_id'),
        ('ability', '0004_remove_ability_pokemons'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='pokemons',
            field=models.ManyToManyField(blank=True, to='pokemon.pokemon'),
        ),
    ]
