# Generated by Django 4.1.7 on 2023-02-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ability', '0005_ability_pokemons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='pokemons',
        ),
    ]
